
# 登录相关配置
login:
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    height: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25

# 配置swagger
swagger:
  version: 1.0v
  groupName: 基础项目
  title: tk—admin 接口文档
  description: 接口文档
  # 扫描的包路径
  basePackage: com.tk